version: '3.8'
 
services:
  web:
    container_name: tracktik-web
    build: .
    ports:
        - 9080:80
    networks:
      - tracktik.network
    volumes:
      - ../:/var/www

  db:
    container_name: tracktik-postgres
    image: postgres:15-alpine
    hostname: localhost
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - tracktik.network

  pgadmin:
    container_name: container-web
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped
    networks:
      - tracktik.network

volumes:
  postgres-data:

networks:
  tracktik.network:
    driver: bridge